#requires -Version 5.1
<#
Regenerates the GridBlock palette from a Minecraft jar's block registry, then
packages the data pack and pushes it to every world that already has it.

The palette is emitted as one `data modify ... set value [...]` command, so
picking a block at run time is a single macro index regardless of palette size.
#>
param(
    [string]$Version = '26.2'
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem

$mc = Join-Path $env:APPDATA '.minecraft'
$jar = Join-Path $mc "versions\$Version\$Version.jar"
$pack = (Resolve-Path (Join-Path $mc 'datapacks\gridblock')).Path

if (-not (Test-Path $jar)) { throw "Jar not found: $jar" }

# --- 1. every block id the game knows about -------------------------------
$z = [System.IO.Compression.ZipFile]::OpenRead($jar)
try {
    $entry = $z.GetEntry('assets/minecraft/lang/en_us.json')
    $reader = New-Object System.IO.StreamReader($entry.Open())
    $lang = $reader.ReadToEnd() | ConvertFrom-Json
    $reader.Dispose()
}
finally { $z.Dispose() }

$all = $lang.PSObject.Properties.Name |
    Where-Object { $_ -match '^block\.minecraft\.([a-z0-9_]+)$' } |
    ForEach-Object { $Matches[1] } |
    Sort-Object -Unique

# --- 2. drop only what genuinely cannot work as a lone floating block -----
# `strict` placement suppresses block and shape updates, so blocks that would
# normally need support (torches, plants, dripstone, sand) survive untouched.

# Invisible, technical, fluid, self-spreading, or mob-spawning.
$denyExact = @(
    'air', 'cave_air', 'void_air', 'water', 'lava', 'bubble_column',
    'fire', 'soul_fire', 'nether_portal', 'end_portal', 'end_gateway',
    'barrier', 'light', 'structure_void', 'structure_block', 'jigsaw',
    'command_block', 'chain_command_block', 'repeating_command_block',
    'moving_piston', 'piston_head', 'bedrock',
    'spawner', 'trial_spawner', 'vault',
    'chorus_flower', 'frosted_ice'
)

# Multi-block or wall-mounted blocks that only make sense as a pair or attached.
$denyPatterns = @('_door$', '_bed$', '^tall_', '^wall_', '_wall_')

$blocks = $all | Where-Object {
    $id = $_
    if ($denyExact -contains $id) { return $false }
    foreach ($p in $denyPatterns) { if ($id -match $p) { return $false } }
    $true
}

if ($blocks.Count -lt 1) { throw 'Palette came out empty - check the filters.' }

# Leaves decay on random ticks regardless of how they were placed.
$entries = $blocks | ForEach-Object {
    if ($_ -match '_leaves$') { "minecraft:$_[persistent=true]" } else { "minecraft:$_" }
}

# --- 3. emit the palette function -----------------------------------------
$list = ($entries | ForEach-Object { '"{0}"' -f $_ }) -join ','
$lines = @(
    '# GENERATED by datapacks/build_gridblock.ps1 - do not edit by hand.',
    "# Source: $Version block registry ($($blocks.Count) of $($all.Count) blocks).",
    "data modify storage gridblock:blocks list set value [$list]"
)
# Set-Content -Encoding UTF8 writes a BOM on Windows PowerShell, which makes
# the first line of an mcfunction unparseable
[System.IO.File]::WriteAllText(
    (Join-Path $pack 'data\gridblock\function\palette.mcfunction'),
    ($lines -join "`n") + "`n",
    (New-Object System.Text.UTF8Encoding $false))

"palette: $($blocks.Count) of $($all.Count) blocks"

# --- 4. package and distribute --------------------------------------------
# Compress-Archive and CreateFromDirectory emit '\' separators, which Minecraft cannot read
$zip = Join-Path ([Environment]::GetFolderPath('Desktop')) 'gridblock.zip'
if (Test-Path $zip) { Remove-Item $zip -Force }

$archive = [System.IO.Compression.ZipFile]::Open($zip, [System.IO.Compression.ZipArchiveMode]::Create)
try {
    foreach ($f in Get-ChildItem -Path $pack -Recurse -File) {
        $rel = $f.FullName.Substring($pack.Length + 1).Replace('\', '/')
        [void][System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
            $archive, $f.FullName, $rel, [System.IO.Compression.CompressionLevel]::Optimal)
    }
}
finally { $archive.Dispose() }

Copy-Item $zip (Join-Path $mc 'datapacks\gridblock.zip') -Force

foreach ($w in Get-ChildItem (Join-Path $mc 'saves') -Directory) {
    $dst = Join-Path $w.FullName 'datapacks\gridblock.zip'
    if (Test-Path $dst) { Copy-Item $zip $dst -Force; "updated: $($w.Name)" }
}
